# Generated by Django 2.2.6 on 2019-10-15 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crypto',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='wallet',
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactionitem', to='api.Crypto')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('total', models.DecimalField(decimal_places=3, max_digits=6)),
                ('Currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='api.Crypto')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Wallet')),
            ],
        ),
    ]
