# Generated by Django 2.2.6 on 2019-10-20 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191015_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16)),
                ('card_name', models.TextField(null=True)),
                ('card_date', models.CharField(max_length=4)),
                ('card_cvv', models.CharField(max_length=3)),
            ],
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='status',
            new_name='is_paid',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='Currency',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='time',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='wallet',
        ),
        migrations.AddField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='transation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactionitem', to='api.Transaction'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
