# Generated by Django 2.2.6 on 2019-10-21 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191020_1235'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreditCard',
        ),
    ]
