# Generated by Django 2.2.6 on 2019-10-22 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191021_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='rate_change',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transations', to='api.Profile'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Crypto'),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='transation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_items', to='api.Transaction'),
        ),
    ]
