# Generated by Django 2.2.6 on 2019-10-22 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191022_0734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionitem',
            old_name='transation',
            new_name='transaction',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='api.Profile'),
        ),
    ]
